In [1]:
# NumPy Solutions
import numpy as np

# Task 1: Create a 1D NumPy array containing integers from 10 to 20
arr_1d = np.arange(10, 21)
print("1D Array:", arr_1d)



1D Array: [10 11 12 13 14 15 16 17 18 19 20]


In [3]:
# Task 2: Difference between .ndim and .shape
example_array = np.array([[1, 2, 3], [4, 5, 6]])
print("Number of dimensions (ndim):", example_array.ndim)
print("Shape of the array (shape):", example_array.shape)



Number of dimensions (ndim): 2
Shape of the array (shape): (2, 3)


In [5]:
# Task 3: Sum of all elements in a NumPy array
array_sum = np.sum(example_array)
print("Sum of elements:", array_sum)



Sum of elements: 21


In [7]:
# Task 4: Extract the first three elements
arr = np.array([5, 10, 15, 20])
first_three = arr[:3]
print("First three elements:", first_three)



First three elements: [ 5 10 15]


In [9]:
# Task 5: Default data type and explicitly setting it to float
default_dtype = np.array([1, 2, 3]).dtype
explicit_float = np.array([1, 2, 3], dtype=float).dtype
print("Default dtype:", default_dtype)
print("Explicit float dtype:", explicit_float)



Default dtype: int32
Explicit float dtype: float64


In [11]:
# Task 6: Element-wise addition and broadcasting
arr1 = np.array([1, 2, 3])
arr2 = np.array([[10], [20], [30]])
sum_array = arr1 + arr2  # Broadcasting
print("Element-wise addition with broadcasting:\n", sum_array)



Element-wise addition with broadcasting:
 [[11 12 13]
 [21 22 23]
 [31 32 33]]


In [13]:
# Task 7: Calculate mean, median, and standard deviation
stats_array = np.array([1, 2, 3, 4, 5])
print("Mean:", np.mean(stats_array))
print("Median:", np.median(stats_array))
print("Standard Deviation:", np.std(stats_array))



Mean: 3.0
Median: 3.0
Standard Deviation: 1.4142135623730951


In [15]:
# Task 8: Reshape 1D array to 2D
reshaped_array = np.arange(12).reshape(3, 4)
print("Reshaped Array:\n", reshaped_array)



Reshaped Array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [17]:
# Task 9: Filter elements greater than 5
arr = np.array([2, 5, 8, 1, 9])
filtered = arr[arr > 5]
print("Filtered elements:", filtered)



Filtered elements: [8 9]


In [19]:
# Task 10: Dot product of two 2D arrays
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
dot_product = np.dot(A, B)
print("Dot product:\n", dot_product)



Dot product:
 [[19 22]
 [43 50]]


In [21]:
# Task 11: Broadcasting explained
# Example: Adding a scalar to a matrix
matrix = np.array([[1, 2], [3, 4]])
scalar = 10
broadcasted_result = matrix + scalar
print("Broadcasting example:\n", broadcasted_result)



Broadcasting example:
 [[11 12]
 [13 14]]


In [23]:
# Task 12: Memory efficiency of NumPy
import sys
list_example = [1, 2, 3, 4, 5]
numpy_array = np.array(list_example)
print("List memory:", sys.getsizeof(list_example))
print("NumPy memory:", numpy_array.nbytes)



List memory: 104
NumPy memory: 20
